
version: '3.9'

services:
  db:
    image: mysql:8.0
    volumes:
      - db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: wordpress
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    networks:
      - site
  
  wordpress:
    depends_on:
      - db
    image: wordpress:5.7-php7.4
    ports:
      - '8000:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORPRESS_DB_HOST: db
      WORPRESS_DB_USER: username
      WORPRESS_DB_PASSWORD: password
    networks:
      - site

networks:
  site:
volumes:
  db:
